server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  datasource:
      url: jdbc:h2:mem:testdb
  application:
    name: PAYMENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service:
      defaultZone: http://localhost:8761/eurekaserver
  instance:
    hostname: localhost
