server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: ORDER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eurekaserver
  instance:
    hostname: localhost
